/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AssurancePackIdRouteImport } from './routes/assurance.$packId'
import { Route as FindingsFindingIdRouteImport } from './routes/findings.$findingId'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows.$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssurancePackIdRoute = AssurancePackIdRouteImport.update({
  id: '/$packId',
  path: '/$packId',
  getParentRoute: () => AssuranceRoute,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/$findingId',
  path: '/$findingId',
  getParentRoute: () => FindingsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRouteWithChildren
  '/findings': typeof FindingsRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/assurance/$packId': typeof AssurancePackIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRouteWithChildren
  '/findings': typeof FindingsRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/assurance/$packId': typeof AssurancePackIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRouteWithChildren
  '/findings': typeof FindingsRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/assurance/$packId': typeof AssurancePackIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance'
    | '/findings'
    | '/policies'
    | '/scenarios'
    | '/settings'
    | '/assurance/$packId'
    | '/findings/$findingId'
    | '/runs/$runId'
    | '/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance'
    | '/findings'
    | '/policies'
    | '/scenarios'
    | '/settings'
    | '/assurance/$packId'
    | '/findings/$findingId'
    | '/runs/$runId'
    | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/assurance'
    | '/findings'
    | '/policies'
    | '/scenarios'
    | '/settings'
    | '/assurance/$packId'
    | '/findings/$findingId'
    | '/runs/$runId'
    | '/workflows/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceRoute: typeof AssuranceRouteWithChildren
  FindingsRoute: typeof FindingsRouteWithChildren
  PoliciesRoute: typeof PoliciesRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance/$packId': {
      id: '/assurance/$packId'
      path: '/$packId'
      fullPath: '/assurance/$packId'
      preLoaderRoute: typeof AssurancePackIdRouteImport
      parentRoute: typeof AssuranceRoute
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof FindingsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssuranceRouteChildren {
  AssurancePackIdRoute: typeof AssurancePackIdRoute
}

const AssuranceRouteChildren: AssuranceRouteChildren = {
  AssurancePackIdRoute: AssurancePackIdRoute,
}

const AssuranceRouteWithChildren = AssuranceRoute._addFileChildren(
  AssuranceRouteChildren,
)

interface FindingsRouteChildren {
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
}

const FindingsRouteChildren: FindingsRouteChildren = {
  FindingsFindingIdRoute: FindingsFindingIdRoute,
}

const FindingsRouteWithChildren = FindingsRoute._addFileChildren(
  FindingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceRoute: AssuranceRouteWithChildren,
  FindingsRoute: FindingsRouteWithChildren,
  PoliciesRoute: PoliciesRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
